### ISSUE TITLE
Consider browse/facet categories

### ISSUE THREAD

**Issue by karindalziel** [CDRH/ardhi#4]
Currently: 

```yaml
facets:
    en:
      collection:
        label: Collection
        flags:
          - search_filter
      category:
        label: Category
        flags:
          - search_filter
      date.year:
        label: Year
        flags:
          - search_filter
      person.name:
        label: People
        flags:
          - search_filter
      languages:
        label: Language
        flags:
          - search_filter
      subcategory:
        label: Subcategory
        flags:
          - search_filter
      creator.name:
        label: Creator
        flags:
          - search_filter
      format:
        label: Format
        flags:
          - search_filter
      places:
        label: Places
        flags:
          - search_filter
```
